import random

from art import blackjack_logo

# This function acts as a random card generator for the deck of cards
def deal_card():
    """Returns a random card from the deck."""
    cards = [11, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 10, 10]
    card = random.choice(cards)
    return card

# This function calculates the score for whichever user it is called with
def calculate_score(cards):
    if sum(cards) == 21 and len(cards) == 2:
        return 0
    if 11 in cards and sum(cards) > 21:
        cards.remove(11)
        cards.append(1)
    return sum(cards)
    """Take a list of cards and return the score calculated from the cards"""


# This function compares the scores of the user and the computer and determines the outcome of the game
def compare(user_score, computer_score):
    if user_score == computer_score:
        return "Draw"
    elif computer_score == 0:
        return "Lose, opponent has Blackjack"
    elif user_score == 0:
        return "Win with a Blackjack"
    elif user_score > 21:
        return "You went over. You lose."
    elif computer_score > 21:
        return "Opponent went over. You Win"
    elif user_score > computer_score:
        return "You win"
    else:
        return "You lose"

# This function is what allows the user to actually play the game
def play_game():
    print(blackjack_logo)
    user_cards = []
    computer_cards = []
    is_game_over = False

    for _ in range(2):  # range(2) because the user and the computer each get 2 cards to start the game
        user_cards.append(
            deal_card())  # For each iteration of the loop, a random card is being generated by deal_card and we're appending that to the list user_cards
        computer_cards.append(
            deal_card())  # For each iteration of the loop, a random card is being generated by deal_card and we're appending that to the list computer_cards

    # While loop for the user to play:
    while not is_game_over:  # While not false...
        user_score = calculate_score(
            user_cards)  # Calling the calculate_score function passing the user_cards variable as the argument
        computer_score = calculate_score(
            computer_cards)  # Calling the calculate_score function passing the computer_cards variable as the argument
        print(f" Your cards: {user_cards}, current score: {user_score}")
        print(f" Computer's first card: {computer_cards[0]}")

        if user_score == 0 or computer_score == 0 or user_score > 21:
            is_game_over = True
        else:
            user_should_deal = input(
                "Type 'y' to get another card, type 'n' to pass: ")
            if user_should_deal == "y":
                user_cards.append(
                    deal_card())  # This will generate another random card per the cards list and append that value to the user_cards list
            else:
                is_game_over = True

    # While loop for the computer to play:
    # This loop is simpler than the human loop because it will automatically add a card if the criteria isn't met where as the user loop gives the user the option.
    while computer_score != 0 and computer_score < 17:
        computer_cards.append(deal_card())
        computer_score = calculate_score(computer_cards)

    print(f" Your final hand: {user_cards}, final score: {user_score}")
    print(f" Computer's final hand: {computer_cards}, final score: {computer_score}")
    print(compare(user_score, computer_score))


while input("Do you want to play a game of Blackjack? Type 'y' or 'n': ") == "y":
    play_game()
